version: '3.3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    command: --acme.email=${ACME_EMAIL} --docker.domain=${DOCKER_DOMAIN}
    ports:
      - 80:80
      - 443:443
      #- 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./log:/log
    container_name: traefik

networks:
  web:
    external: true
